"""empty message

Revision ID: 6c3b94347a6b
Revises: ff6dde5bef30
Create Date: 2016-05-24 23:45:10.889716

"""

# revision identifiers, used by Alembic.
revision = '6c3b94347a6b'
down_revision = 'ff6dde5bef30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('day_rank', sa.Integer(), nullable=True))
    op.drop_column('entries', 'score')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('entries', 'day_rank')
    ### end Alembic commands ###
