"""empty message

Revision ID: f7c74eaefdce
Revises: None
Create Date: 2016-06-29 00:36:33.161357

"""

# revision identifiers, used by Alembic.
revision = 'f7c74eaefdce'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    ### end Alembic commands ###
