"""empty message

Revision ID: ff6dde5bef30
Revises: 9cdb95944597
Create Date: 2016-05-24 22:37:37.766432

"""

# revision identifiers, used by Alembic.
revision = 'ff6dde5bef30'
down_revision = '9cdb95944597'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('score', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'score')
    ### end Alembic commands ###
